"""
One-time script: append P005 and P006 data to all raw JSON files.
Run: python scripts/add_p005_p006.py
"""
import json
from pathlib import Path

RAW = Path(__file__).parent.parent / "data" / "raw"


def _load(name):
    return json.loads((RAW / name).read_text(encoding="utf-8"))


def _save(name, data):
    (RAW / name).write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"  {name}: {len(data)} records")


def add_labs():
    labs = _load("labs.json")
    new = [
        # ── P005-E001 ──
        {"lab_id": "P005-E001-LAB001", "patient_id": "P005", "encounter_id": "P005-E001",
         "sample_date": "2024-01-15", "result_date": "2024-01-15",
         "test_code": "BNP", "test_name": "BNP (Brain Natriuretic Peptide)",
         "value": 680, "unit": "pg/mL", "reference_range": "< 100",
         "interpretation": "high", "comment": "Tăng cao, phù hợp suy tim mất bù.",
         "source_system": "LIS", "is_abnormal": True, "is_critical": True},
        {"lab_id": "P005-E001-LAB002", "patient_id": "P005", "encounter_id": "P005-E001",
         "sample_date": "2024-01-15", "result_date": "2024-01-15",
         "test_code": "HCT", "test_name": "Hematocrit",
         "value": 54, "unit": "%", "reference_range": "40 - 50",
         "interpretation": "high", "comment": "Đa hồng cầu thứ phát do thiếu oxy mạn tính.",
         "source_system": "LIS", "is_abnormal": True, "is_critical": False},
        {"lab_id": "P005-E001-LAB003", "patient_id": "P005", "encounter_id": "P005-E001",
         "sample_date": "2024-01-15", "result_date": "2024-01-15",
         "test_code": "CREAT", "test_name": "Creatinine",
         "value": 98, "unit": "µmol/L", "reference_range": "62 - 106",
         "interpretation": "normal", "comment": "Chức năng thận bình thường.",
         "source_system": "LIS", "is_abnormal": False, "is_critical": False},
        {"lab_id": "P005-E001-LAB004", "patient_id": "P005", "encounter_id": "P005-E001",
         "sample_date": "2024-01-15", "result_date": "2024-01-15",
         "test_code": "PAO2", "test_name": "PaO2 (khí máu động mạch)",
         "value": 56, "unit": "mmHg", "reference_range": "80 - 100",
         "interpretation": "low", "comment": "Giảm oxy máu nặng. Cần oxy liệu pháp.",
         "source_system": "LIS", "is_abnormal": True, "is_critical": True},
        {"lab_id": "P005-E001-LAB005", "patient_id": "P005", "encounter_id": "P005-E001",
         "sample_date": "2024-01-15", "result_date": "2024-01-15",
         "test_code": "PACO2", "test_name": "PaCO2 (khí máu động mạch)",
         "value": 52, "unit": "mmHg", "reference_range": "35 - 45",
         "interpretation": "high", "comment": "Tăng CO2 máu, suy hô hấp type 2.",
         "source_system": "LIS", "is_abnormal": True, "is_critical": False},
        # ── P005-E002 ──
        {"lab_id": "P005-E002-LAB001", "patient_id": "P005", "encounter_id": "P005-E002",
         "sample_date": "2024-07-15", "result_date": "2024-07-15",
         "test_code": "BNP", "test_name": "BNP (Brain Natriuretic Peptide)",
         "value": 420, "unit": "pg/mL", "reference_range": "< 100",
         "interpretation": "high", "comment": "Giảm so với lần trước (680), suy tim cải thiện.",
         "source_system": "LIS", "is_abnormal": True, "is_critical": False},
        {"lab_id": "P005-E002-LAB002", "patient_id": "P005", "encounter_id": "P005-E002",
         "sample_date": "2024-07-15", "result_date": "2024-07-15",
         "test_code": "FEV1", "test_name": "FEV1 (% dự đoán)",
         "value": 42, "unit": "%", "reference_range": "> 80",
         "interpretation": "low", "comment": "COPD Gold III (30-49%). Tắc nghẽ nặng.",
         "source_system": "LIS", "is_abnormal": True, "is_critical": False},
        {"lab_id": "P005-E002-LAB003", "patient_id": "P005", "encounter_id": "P005-E002",
         "sample_date": "2024-07-15", "result_date": "2024-07-15",
         "test_code": "SPO2REST", "test_name": "SpO2 nghỉ ngơi",
         "value": 88, "unit": "%", "reference_range": "> 95",
         "interpretation": "low", "comment": "Giảm oxy máu mức trung bình khi nghỉ.",
         "source_system": "LIS", "is_abnormal": True, "is_critical": False},
        # ── P005-E003 ──
        {"lab_id": "P005-E003-LAB001", "patient_id": "P005", "encounter_id": "P005-E003",
         "sample_date": "2024-10-15", "result_date": "2024-10-15",
         "test_code": "BNP", "test_name": "BNP (Brain Natriuretic Peptide)",
         "value": 380, "unit": "pg/mL", "reference_range": "< 100",
         "interpretation": "high", "comment": "Tiếp tục giảm (680 → 420 → 380). Xu hướng cải thiện.",
         "source_system": "LIS", "is_abnormal": True, "is_critical": False},
        {"lab_id": "P005-E003-LAB002", "patient_id": "P005", "encounter_id": "P005-E003",
         "sample_date": "2024-10-15", "result_date": "2024-10-15",
         "test_code": "CREAT", "test_name": "Creatinine",
         "value": 102, "unit": "µmol/L", "reference_range": "62 - 106",
         "interpretation": "normal", "comment": "Chức năng thận ổn định.",
         "source_system": "LIS", "is_abnormal": False, "is_critical": False},
        # ── P006-E001 ──
        {"lab_id": "P006-E001-LAB001", "patient_id": "P006", "encounter_id": "P006-E001",
         "sample_date": "2024-03-10", "result_date": "2024-03-10",
         "test_code": "HBA1C", "test_name": "HbA1c (Hemoglobin glycated)",
         "value": 9.8, "unit": "%", "reference_range": "4.0 - 5.6",
         "interpretation": "high", "comment": "Kiểm soát đường huyết rất kém.",
         "source_system": "LIS", "is_abnormal": True, "is_critical": False},
        {"lab_id": "P006-E001-LAB002", "patient_id": "P006", "encounter_id": "P006-E001",
         "sample_date": "2024-03-10", "result_date": "2024-03-10",
         "test_code": "FPG", "test_name": "Glucose huyết tương lúc đói",
         "value": 12.4, "unit": "mmol/L", "reference_range": "3.9 - 6.1",
         "interpretation": "high", "comment": "Tăng cao.",
         "source_system": "LIS", "is_abnormal": True, "is_critical": False},
        {"lab_id": "P006-E001-LAB003", "patient_id": "P006", "encounter_id": "P006-E001",
         "sample_date": "2024-03-10", "result_date": "2024-03-10",
         "test_code": "CREAT", "test_name": "Creatinine",
         "value": 175, "unit": "µmol/L", "reference_range": "45 - 84",
         "interpretation": "high", "comment": "Tăng cao, phù hợp CKD giai đoạn 3b.",
         "source_system": "LIS", "is_abnormal": True, "is_critical": True},
        {"lab_id": "P006-E001-LAB004", "patient_id": "P006", "encounter_id": "P006-E001",
         "sample_date": "2024-03-10", "result_date": "2024-03-10",
         "test_code": "EGFR", "test_name": "eGFR (CKD-EPI)",
         "value": 38, "unit": "mL/min/1.73m2", "reference_range": "> 90",
         "interpretation": "low", "comment": "CKD giai đoạn 3b (eGFR 30-44).",
         "source_system": "LIS", "is_abnormal": True, "is_critical": True},
        {"lab_id": "P006-E001-LAB005", "patient_id": "P006", "encounter_id": "P006-E001",
         "sample_date": "2024-03-10", "result_date": "2024-03-10",
         "test_code": "UACR", "test_name": "Tỷ số Albumin/Creatinine nước tiểu",
         "value": 2800, "unit": "mg/g", "reference_range": "< 30",
         "interpretation": "high", "comment": "Macroalbuminuria nặng (A3).",
         "source_system": "LIS", "is_abnormal": True, "is_critical": True},
        {"lab_id": "P006-E001-LAB006", "patient_id": "P006", "encounter_id": "P006-E001",
         "sample_date": "2024-03-10", "result_date": "2024-03-10",
         "test_code": "K", "test_name": "Kali máu",
         "value": 5.1, "unit": "mmol/L", "reference_range": "3.5 - 5.0",
         "interpretation": "high", "comment": "Tăng nhẹ, cần theo dõi do CKD + ARB.",
         "source_system": "LIS", "is_abnormal": True, "is_critical": False},
        {"lab_id": "P006-E001-LAB007", "patient_id": "P006", "encounter_id": "P006-E001",
         "sample_date": "2024-03-10", "result_date": "2024-03-10",
         "test_code": "PHOS", "test_name": "Phosphate",
         "value": 1.55, "unit": "mmol/L", "reference_range": "0.8 - 1.45",
         "interpretation": "high", "comment": "Tăng phosphate do giảm đào thải thận.",
         "source_system": "LIS", "is_abnormal": True, "is_critical": False},
        {"lab_id": "P006-E001-LAB008", "patient_id": "P006", "encounter_id": "P006-E001",
         "sample_date": "2024-03-10", "result_date": "2024-03-10",
         "test_code": "BUN", "test_name": "BUN (Blood Urea Nitrogen)",
         "value": 14.2, "unit": "mmol/L", "reference_range": "2.5 - 7.1",
         "interpretation": "high", "comment": "Tăng ure máu.",
         "source_system": "LIS", "is_abnormal": True, "is_critical": False},
        # ── P006-E002 ──
        {"lab_id": "P006-E002-LAB001", "patient_id": "P006", "encounter_id": "P006-E002",
         "sample_date": "2024-09-10", "result_date": "2024-09-10",
         "test_code": "HBA1C", "test_name": "HbA1c (Hemoglobin glycated)",
         "value": 8.9, "unit": "%", "reference_range": "4.0 - 5.6",
         "interpretation": "high", "comment": "Cải thiện nhẹ so với 9.8%.",
         "source_system": "LIS", "is_abnormal": True, "is_critical": False},
        {"lab_id": "P006-E002-LAB002", "patient_id": "P006", "encounter_id": "P006-E002",
         "sample_date": "2024-09-10", "result_date": "2024-09-10",
         "test_code": "CREAT", "test_name": "Creatinine",
         "value": 182, "unit": "µmol/L", "reference_range": "45 - 84",
         "interpretation": "high", "comment": "Tăng so với 175. CKD tiến triển.",
         "source_system": "LIS", "is_abnormal": True, "is_critical": True},
        {"lab_id": "P006-E002-LAB003", "patient_id": "P006", "encounter_id": "P006-E002",
         "sample_date": "2024-09-10", "result_date": "2024-09-10",
         "test_code": "EGFR", "test_name": "eGFR (CKD-EPI)",
         "value": 35, "unit": "mL/min/1.73m2", "reference_range": "> 90",
         "interpretation": "low", "comment": "Giảm so với 38.",
         "source_system": "LIS", "is_abnormal": True, "is_critical": True},
        {"lab_id": "P006-E002-LAB004", "patient_id": "P006", "encounter_id": "P006-E002",
         "sample_date": "2024-09-10", "result_date": "2024-09-10",
         "test_code": "UACR", "test_name": "Tỷ số Albumin/Creatinine nước tiểu",
         "value": 2200, "unit": "mg/g", "reference_range": "< 30",
         "interpretation": "high", "comment": "Giảm so với 2800, đáp ứng điều trị.",
         "source_system": "LIS", "is_abnormal": True, "is_critical": True},
        {"lab_id": "P006-E002-LAB005", "patient_id": "P006", "encounter_id": "P006-E002",
         "sample_date": "2024-09-10", "result_date": "2024-09-10",
         "test_code": "HGB", "test_name": "Hemoglobin",
         "value": 10.2, "unit": "g/dL", "reference_range": "12.0 - 16.0",
         "interpretation": "low", "comment": "Thiếu máu mức trung bình do CKD.",
         "source_system": "LIS", "is_abnormal": True, "is_critical": False},
    ]
    labs.extend(new)
    _save("labs.json", labs)


def add_medications():
    meds = _load("medications.json")
    new = [
        # ── P005-E001 ──
        {"medication_id": "P005-E001-MED001", "patient_id": "P005", "encounter_id": "P005-E001",
         "prescription_date": "2024-01-15", "drug_name": "Tiotropium", "strength": "18 mcg",
         "dose": "1 nhát hít", "route": "inhalation", "frequency": "1 lần/ngày buổi sáng",
         "instruction": "Hít qua dụng cụ HandiHaler. Không nuốt viên nang.",
         "duration_days": 180, "is_current": True, "source_system": "HIS-Pharmacy", "language": "vi"},
        {"medication_id": "P005-E001-MED002", "patient_id": "P005", "encounter_id": "P005-E001",
         "prescription_date": "2024-01-15", "drug_name": "Salbutamol", "strength": "100 mcg",
         "dose": "2 nhát xịt", "route": "inhalation", "frequency": "khi cần (tối đa 4 lần/ngày)",
         "instruction": "Xịt khi khó thở cấp. Lắc bình trước khi dùng.",
         "duration_days": 90, "is_current": True, "source_system": "HIS-Pharmacy", "language": "vi"},
        {"medication_id": "P005-E001-MED003", "patient_id": "P005", "encounter_id": "P005-E001",
         "prescription_date": "2024-01-15", "drug_name": "Methylprednisolone", "strength": "40 mg",
         "dose": "1 viên", "route": "oral", "frequency": "1 lần/ngày buổi sáng",
         "instruction": "Giảm liều dần trong 7 ngày. Dùng cho đợt cấp COPD.",
         "duration_days": 7, "is_current": False, "source_system": "HIS-Pharmacy", "language": "vi"},
        {"medication_id": "P005-E001-MED004", "patient_id": "P005", "encounter_id": "P005-E001",
         "prescription_date": "2024-01-15", "drug_name": "Furosemide", "strength": "40 mg",
         "dose": "1 viên", "route": "oral", "frequency": "1 lần/ngày buổi sáng",
         "instruction": "Uống buổi sáng lúc đói. Theo dõi kali máu.",
         "duration_days": 90, "is_current": True, "source_system": "HIS-Pharmacy", "language": "vi"},
        {"medication_id": "P005-E001-MED005", "patient_id": "P005", "encounter_id": "P005-E001",
         "prescription_date": "2024-01-15", "drug_name": "Carvedilol", "strength": "6.25 mg",
         "dose": "1 viên", "route": "oral", "frequency": "2 lần/ngày (sáng và tối)",
         "instruction": "Uống cùng bữa ăn. Liều khởi đầu thấp do suy tim.",
         "duration_days": 90, "is_current": True, "source_system": "HIS-Pharmacy", "language": "vi"},
        {"medication_id": "P005-E001-MED006", "patient_id": "P005", "encounter_id": "P005-E001",
         "prescription_date": "2024-01-15", "drug_name": "Amlodipine", "strength": "5 mg",
         "dose": "1 viên", "route": "oral", "frequency": "1 lần/ngày buổi sáng",
         "instruction": "Uống buổi sáng. Hạ huyết áp.",
         "duration_days": 90, "is_current": True, "source_system": "HIS-Pharmacy", "language": "vi"},
        {"medication_id": "P005-E001-MED007", "patient_id": "P005", "encounter_id": "P005-E001",
         "prescription_date": "2024-01-15", "drug_name": "Enalapril", "strength": "5 mg",
         "dose": "1 viên", "route": "oral", "frequency": "1 lần/ngày buổi sáng",
         "instruction": "Ức chế men chuyển. Theo dõi kali và creatinine.",
         "duration_days": 90, "is_current": True, "source_system": "HIS-Pharmacy", "language": "vi"},
        # ── P005-E002 ──
        {"medication_id": "P005-E002-MED001", "patient_id": "P005", "encounter_id": "P005-E002",
         "prescription_date": "2024-07-15", "drug_name": "Tiotropium", "strength": "18 mcg",
         "dose": "1 nhát hít", "route": "inhalation", "frequency": "1 lần/ngày buổi sáng",
         "instruction": "Tiếp tục duy trì.", "duration_days": 90, "is_current": True,
         "source_system": "HIS-Pharmacy", "language": "vi"},
        {"medication_id": "P005-E002-MED002", "patient_id": "P005", "encounter_id": "P005-E002",
         "prescription_date": "2024-07-15", "drug_name": "Fluticasone/Salmeterol", "strength": "500/50 mcg",
         "dose": "1 nhát hít", "route": "inhalation", "frequency": "2 lần/ngày (sáng và tối)",
         "instruction": "Hít qua Diskus. Súc miệng sau khi dùng.",
         "duration_days": 90, "is_current": True, "source_system": "HIS-Pharmacy", "language": "vi"},
        {"medication_id": "P005-E002-MED003", "patient_id": "P005", "encounter_id": "P005-E002",
         "prescription_date": "2024-07-15", "drug_name": "Furosemide", "strength": "40 mg",
         "dose": "1 viên", "route": "oral", "frequency": "1 lần/ngày buổi sáng",
         "instruction": "Duy trì.", "duration_days": 90, "is_current": True,
         "source_system": "HIS-Pharmacy", "language": "vi"},
        {"medication_id": "P005-E002-MED004", "patient_id": "P005", "encounter_id": "P005-E002",
         "prescription_date": "2024-07-15", "drug_name": "Carvedilol", "strength": "12.5 mg",
         "dose": "1 viên", "route": "oral", "frequency": "2 lần/ngày (sáng và tối)",
         "instruction": "Tăng liều từ 6.25mg. Dung nạp tốt.",
         "duration_days": 90, "is_current": True, "source_system": "HIS-Pharmacy", "language": "vi"},
        {"medication_id": "P005-E002-MED005", "patient_id": "P005", "encounter_id": "P005-E002",
         "prescription_date": "2024-07-15", "drug_name": "Enalapril", "strength": "10 mg",
         "dose": "1 viên", "route": "oral", "frequency": "1 lần/ngày buổi sáng",
         "instruction": "Tăng liều từ 5mg.", "duration_days": 90, "is_current": True,
         "source_system": "HIS-Pharmacy", "language": "vi"},
        {"medication_id": "P005-E002-MED006", "patient_id": "P005", "encounter_id": "P005-E002",
         "prescription_date": "2024-07-15", "drug_name": "Amlodipine", "strength": "5 mg",
         "dose": "1 viên", "route": "oral", "frequency": "1 lần/ngày buổi sáng",
         "instruction": "Duy trì.", "duration_days": 90, "is_current": True,
         "source_system": "HIS-Pharmacy", "language": "vi"},
        # ── P005-E003 ──
        {"medication_id": "P005-E003-MED001", "patient_id": "P005", "encounter_id": "P005-E003",
         "prescription_date": "2024-10-15", "drug_name": "Tiotropium", "strength": "18 mcg",
         "dose": "1 nhát hít", "route": "inhalation", "frequency": "1 lần/ngày buổi sáng",
         "instruction": "Duy trì.", "duration_days": 90, "is_current": True,
         "source_system": "HIS-Pharmacy", "language": "vi"},
        {"medication_id": "P005-E003-MED002", "patient_id": "P005", "encounter_id": "P005-E003",
         "prescription_date": "2024-10-15", "drug_name": "Fluticasone/Salmeterol", "strength": "500/50 mcg",
         "dose": "1 nhát hít", "route": "inhalation", "frequency": "2 lần/ngày (sáng và tối)",
         "instruction": "Duy trì.", "duration_days": 90, "is_current": True,
         "source_system": "HIS-Pharmacy", "language": "vi"},
        {"medication_id": "P005-E003-MED003", "patient_id": "P005", "encounter_id": "P005-E003",
         "prescription_date": "2024-10-15", "drug_name": "Furosemide", "strength": "40 mg",
         "dose": "1 viên", "route": "oral", "frequency": "1 lần/ngày buổi sáng",
         "instruction": "Duy trì.", "duration_days": 90, "is_current": True,
         "source_system": "HIS-Pharmacy", "language": "vi"},
        {"medication_id": "P005-E003-MED004", "patient_id": "P005", "encounter_id": "P005-E003",
         "prescription_date": "2024-10-15", "drug_name": "Carvedilol", "strength": "12.5 mg",
         "dose": "1 viên", "route": "oral", "frequency": "2 lần/ngày (sáng và tối)",
         "instruction": "Duy trì.", "duration_days": 90, "is_current": True,
         "source_system": "HIS-Pharmacy", "language": "vi"},
        {"medication_id": "P005-E003-MED005", "patient_id": "P005", "encounter_id": "P005-E003",
         "prescription_date": "2024-10-15", "drug_name": "Enalapril", "strength": "10 mg",
         "dose": "1 viên", "route": "oral", "frequency": "1 lần/ngày buổi sáng",
         "instruction": "Duy trì.", "duration_days": 90, "is_current": True,
         "source_system": "HIS-Pharmacy", "language": "vi"},
        {"medication_id": "P005-E003-MED006", "patient_id": "P005", "encounter_id": "P005-E003",
         "prescription_date": "2024-10-15", "drug_name": "Amlodipine", "strength": "5 mg",
         "dose": "1 viên", "route": "oral", "frequency": "1 lần/ngày buổi sáng",
         "instruction": "Duy trì.", "duration_days": 90, "is_current": True,
         "source_system": "HIS-Pharmacy", "language": "vi"},
        {"medication_id": "P005-E003-MED007", "patient_id": "P005", "encounter_id": "P005-E003",
         "prescription_date": "2024-10-15", "drug_name": "Spironolactone", "strength": "25 mg",
         "dose": "1 viên", "route": "oral", "frequency": "1 lần/ngày buổi sáng",
         "instruction": "Thêm mới. Kháng aldosterone cho suy tim EF giảm. Theo dõi kali.",
         "duration_days": 90, "is_current": True, "source_system": "HIS-Pharmacy", "language": "vi"},
        # ── P006-E001 ──
        {"medication_id": "P006-E001-MED001", "patient_id": "P006", "encounter_id": "P006-E001",
         "prescription_date": "2024-03-10", "drug_name": "Insulin Glargine", "strength": "100 IU/mL",
         "dose": "20 IU", "route": "subcutaneous", "frequency": "1 lần/ngày trước ngủ",
         "instruction": "Tiêm dưới da vùng bụng hoặc đùi. Metformin chống chỉ định (eGFR <45).",
         "duration_days": 180, "is_current": True, "source_system": "HIS-Pharmacy", "language": "vi"},
        {"medication_id": "P006-E001-MED002", "patient_id": "P006", "encounter_id": "P006-E001",
         "prescription_date": "2024-03-10", "drug_name": "Losartan", "strength": "100 mg",
         "dose": "1 viên", "route": "oral", "frequency": "1 lần/ngày buổi sáng",
         "instruction": "Chẹn thụ thể AT1. Bảo vệ thận + hạ HA. Theo dõi kali.",
         "duration_days": 180, "is_current": True, "source_system": "HIS-Pharmacy", "language": "vi"},
        {"medication_id": "P006-E001-MED003", "patient_id": "P006", "encounter_id": "P006-E001",
         "prescription_date": "2024-03-10", "drug_name": "Amlodipine", "strength": "5 mg",
         "dose": "1 viên", "route": "oral", "frequency": "1 lần/ngày buổi sáng",
         "instruction": "Hạ huyết áp. Mục tiêu HA <130/80.",
         "duration_days": 180, "is_current": True, "source_system": "HIS-Pharmacy", "language": "vi"},
        {"medication_id": "P006-E001-MED004", "patient_id": "P006", "encounter_id": "P006-E001",
         "prescription_date": "2024-03-10", "drug_name": "Calcitriol", "strength": "0.25 mcg",
         "dose": "1 viên", "route": "oral", "frequency": "1 lần/ngày",
         "instruction": "Vitamin D hoạt hóa cho CKD. Theo dõi canxi máu.",
         "duration_days": 180, "is_current": True, "source_system": "HIS-Pharmacy", "language": "vi"},
        {"medication_id": "P006-E001-MED005", "patient_id": "P006", "encounter_id": "P006-E001",
         "prescription_date": "2024-03-10", "drug_name": "Calcium carbonate", "strength": "500 mg",
         "dose": "1 viên", "route": "oral", "frequency": "3 lần/ngày cùng bữa ăn",
         "instruction": "Gắn phosphate trong ruột. Uống cùng bữa ăn.",
         "duration_days": 180, "is_current": True, "source_system": "HIS-Pharmacy", "language": "vi"},
        {"medication_id": "P006-E001-MED006", "patient_id": "P006", "encounter_id": "P006-E001",
         "prescription_date": "2024-03-10", "drug_name": "Sắt sulfate", "strength": "300 mg",
         "dose": "1 viên", "route": "oral", "frequency": "1 lần/ngày",
         "instruction": "Bổ sung sắt. Uống lúc đói.",
         "duration_days": 90, "is_current": True, "source_system": "HIS-Pharmacy", "language": "vi"},
        # ── P006-E002 ──
        {"medication_id": "P006-E002-MED001", "patient_id": "P006", "encounter_id": "P006-E002",
         "prescription_date": "2024-09-10", "drug_name": "Insulin Glargine", "strength": "100 IU/mL",
         "dose": "24 IU", "route": "subcutaneous", "frequency": "1 lần/ngày trước ngủ",
         "instruction": "Tăng liều từ 20 IU. Theo dõi glucose lúc đói.",
         "duration_days": 180, "is_current": True, "source_system": "HIS-Pharmacy", "language": "vi"},
        {"medication_id": "P006-E002-MED002", "patient_id": "P006", "encounter_id": "P006-E002",
         "prescription_date": "2024-09-10", "drug_name": "Losartan", "strength": "100 mg",
         "dose": "1 viên", "route": "oral", "frequency": "1 lần/ngày buổi sáng",
         "instruction": "Duy trì.", "duration_days": 180, "is_current": True,
         "source_system": "HIS-Pharmacy", "language": "vi"},
        {"medication_id": "P006-E002-MED003", "patient_id": "P006", "encounter_id": "P006-E002",
         "prescription_date": "2024-09-10", "drug_name": "Amlodipine", "strength": "10 mg",
         "dose": "1 viên", "route": "oral", "frequency": "1 lần/ngày buổi sáng",
         "instruction": "Tăng liều từ 5mg. HA chưa đạt mục tiêu.",
         "duration_days": 180, "is_current": True, "source_system": "HIS-Pharmacy", "language": "vi"},
        {"medication_id": "P006-E002-MED004", "patient_id": "P006", "encounter_id": "P006-E002",
         "prescription_date": "2024-09-10", "drug_name": "Dapagliflozin", "strength": "10 mg",
         "dose": "1 viên", "route": "oral", "frequency": "1 lần/ngày buổi sáng",
         "instruction": "SGLT2i. Giảm protein niệu + bảo vệ thận. An toàn khi eGFR >25.",
         "duration_days": 180, "is_current": True, "source_system": "HIS-Pharmacy", "language": "vi"},
        {"medication_id": "P006-E002-MED005", "patient_id": "P006", "encounter_id": "P006-E002",
         "prescription_date": "2024-09-10", "drug_name": "Erythropoietin", "strength": "2000 IU",
         "dose": "1 ống tiêm", "route": "subcutaneous", "frequency": "3 lần/tuần",
         "instruction": "EPO cho thiếu máu do CKD. Mục tiêu Hb 10-11.5 g/dL.",
         "duration_days": 90, "is_current": True, "source_system": "HIS-Pharmacy", "language": "vi"},
        {"medication_id": "P006-E002-MED006", "patient_id": "P006", "encounter_id": "P006-E002",
         "prescription_date": "2024-09-10", "drug_name": "Calcitriol", "strength": "0.25 mcg",
         "dose": "1 viên", "route": "oral", "frequency": "1 lần/ngày",
         "instruction": "Duy trì.", "duration_days": 180, "is_current": True,
         "source_system": "HIS-Pharmacy", "language": "vi"},
        {"medication_id": "P006-E002-MED007", "patient_id": "P006", "encounter_id": "P006-E002",
         "prescription_date": "2024-09-10", "drug_name": "Calcium carbonate", "strength": "500 mg",
         "dose": "1 viên", "route": "oral", "frequency": "3 lần/ngày cùng bữa ăn",
         "instruction": "Duy trì.", "duration_days": 180, "is_current": True,
         "source_system": "HIS-Pharmacy", "language": "vi"},
    ]
    meds.extend(new)
    _save("medications.json", meds)


def add_diagnoses():
    dx = _load("diagnoses.json")
    new = [
        # ── P005-E001 ──
        {"diagnosis_id": "P005-E001-DX001", "patient_id": "P005", "encounter_id": "P005-E001",
         "diagnosis_date": "2024-01-15", "diagnosis_type": "primary", "icd10_code": "J44.1",
         "diagnosis_name": "COPD với đợt cấp",
         "diagnosis_text": "COPD Gold III đợt cấp. FEV1 42% dự đoán. Ho đàm vàng, khó thở MRC grade 4. SpO2 84% khí phòng.",
         "is_active": True, "source_system": "HIS-Diagnosis", "language": "vi"},
        {"diagnosis_id": "P005-E001-DX002", "patient_id": "P005", "encounter_id": "P005-E001",
         "diagnosis_date": "2024-01-15", "diagnosis_type": "comorbidity", "icd10_code": "I50.1",
         "diagnosis_name": "Suy tim trái, phân suất tống máu giảm",
         "diagnosis_text": "Suy tim EF giảm (EF 35%). BNP 680 pg/mL. Phù mắt cá nhẹ.",
         "is_active": True, "source_system": "HIS-Diagnosis", "language": "vi"},
        {"diagnosis_id": "P005-E001-DX003", "patient_id": "P005", "encounter_id": "P005-E001",
         "diagnosis_date": "2024-01-15", "diagnosis_type": "comorbidity", "icd10_code": "I27.9",
         "diagnosis_name": "Tăng áp phổi / Tim phổi mạn tính",
         "diagnosis_text": "Tim phổi mạn do COPD. Thất phải giãn trên siêu âm.",
         "is_active": True, "source_system": "HIS-Diagnosis", "language": "vi"},
        {"diagnosis_id": "P005-E001-DX004", "patient_id": "P005", "encounter_id": "P005-E001",
         "diagnosis_date": "2024-01-15", "diagnosis_type": "comorbidity", "icd10_code": "I10",
         "diagnosis_name": "Tăng huyết áp nguyên phát",
         "diagnosis_text": "THA. HA 155/95 mmHg.",
         "is_active": True, "source_system": "HIS-Diagnosis", "language": "vi"},
        # ── P005-E002 ──
        {"diagnosis_id": "P005-E002-DX001", "patient_id": "P005", "encounter_id": "P005-E002",
         "diagnosis_date": "2024-07-15", "diagnosis_type": "primary", "icd10_code": "J44.0",
         "diagnosis_name": "COPD ổn định",
         "diagnosis_text": "COPD Gold III giai đoạn ổn định sau đợt cấp. FEV1 42%. SpO2 88% nghỉ ngơi.",
         "is_active": True, "source_system": "HIS-Diagnosis", "language": "vi"},
        {"diagnosis_id": "P005-E002-DX002", "patient_id": "P005", "encounter_id": "P005-E002",
         "diagnosis_date": "2024-07-15", "diagnosis_type": "comorbidity", "icd10_code": "I50.1",
         "diagnosis_name": "Suy tim trái, phân suất tống máu giảm",
         "diagnosis_text": "Suy tim EF 35%. BNP giảm 420 pg/mL. Cải thiện so với lần trước.",
         "is_active": True, "source_system": "HIS-Diagnosis", "language": "vi"},
        {"diagnosis_id": "P005-E002-DX003", "patient_id": "P005", "encounter_id": "P005-E002",
         "diagnosis_date": "2024-07-15", "diagnosis_type": "comorbidity", "icd10_code": "I10",
         "diagnosis_name": "Tăng huyết áp nguyên phát",
         "diagnosis_text": "THA. HA 138/85 mmHg, cải thiện.",
         "is_active": True, "source_system": "HIS-Diagnosis", "language": "vi"},
        # ── P005-E003 ──
        {"diagnosis_id": "P005-E003-DX001", "patient_id": "P005", "encounter_id": "P005-E003",
         "diagnosis_date": "2024-10-15", "diagnosis_type": "primary", "icd10_code": "J44.0",
         "diagnosis_name": "COPD ổn định",
         "diagnosis_text": "COPD Gold III ổn định. Không đợt cấp 9 tháng qua.",
         "is_active": True, "source_system": "HIS-Diagnosis", "language": "vi"},
        {"diagnosis_id": "P005-E003-DX002", "patient_id": "P005", "encounter_id": "P005-E003",
         "diagnosis_date": "2024-10-15", "diagnosis_type": "comorbidity", "icd10_code": "I50.1",
         "diagnosis_name": "Suy tim trái, phân suất tống máu giảm",
         "diagnosis_text": "Suy tim EF giảm. BNP 380 pg/mL. Phù mắt cá tăng nhẹ. Thêm Spironolactone.",
         "is_active": True, "source_system": "HIS-Diagnosis", "language": "vi"},
        {"diagnosis_id": "P005-E003-DX003", "patient_id": "P005", "encounter_id": "P005-E003",
         "diagnosis_date": "2024-10-15", "diagnosis_type": "comorbidity", "icd10_code": "I10",
         "diagnosis_name": "Tăng huyết áp nguyên phát",
         "diagnosis_text": "THA. HA 135/82 mmHg.",
         "is_active": True, "source_system": "HIS-Diagnosis", "language": "vi"},
        # ── P006-E001 ──
        {"diagnosis_id": "P006-E001-DX001", "patient_id": "P006", "encounter_id": "P006-E001",
         "diagnosis_date": "2024-03-10", "diagnosis_type": "primary", "icd10_code": "E11.65",
         "diagnosis_name": "ĐTĐ type 2 với biến chứng thận mạn",
         "diagnosis_text": "ĐTĐ type 2 kiểm soát rất kém (HbA1c 9.8%). Biến chứng bệnh thận mạn giai đoạn 3b.",
         "is_active": True, "source_system": "HIS-Diagnosis", "language": "vi"},
        {"diagnosis_id": "P006-E001-DX002", "patient_id": "P006", "encounter_id": "P006-E001",
         "diagnosis_date": "2024-03-10", "diagnosis_type": "comorbidity", "icd10_code": "N18.3",
         "diagnosis_name": "Bệnh thận mạn giai đoạn 3b",
         "diagnosis_text": "CKD G3b A3 (eGFR 38, UACR 2800 mg/g). Nguyên nhân: biến chứng ĐTĐ.",
         "is_active": True, "source_system": "HIS-Diagnosis", "language": "vi"},
        {"diagnosis_id": "P006-E001-DX003", "patient_id": "P006", "encounter_id": "P006-E001",
         "diagnosis_date": "2024-03-10", "diagnosis_type": "comorbidity", "icd10_code": "I10",
         "diagnosis_name": "Tăng huyết áp nguyên phát",
         "diagnosis_text": "THA 3 năm. HA 162/98 mmHg, chưa đạt mục tiêu <130/80.",
         "is_active": True, "source_system": "HIS-Diagnosis", "language": "vi"},
        # ── P006-E002 ──
        {"diagnosis_id": "P006-E002-DX001", "patient_id": "P006", "encounter_id": "P006-E002",
         "diagnosis_date": "2024-09-10", "diagnosis_type": "primary", "icd10_code": "E11.65",
         "diagnosis_name": "ĐTĐ type 2 với biến chứng thận mạn",
         "diagnosis_text": "ĐTĐ type 2 cải thiện nhẹ (HbA1c 8.9%). CKD tiến triển (eGFR 35).",
         "is_active": True, "source_system": "HIS-Diagnosis", "language": "vi"},
        {"diagnosis_id": "P006-E002-DX002", "patient_id": "P006", "encounter_id": "P006-E002",
         "diagnosis_date": "2024-09-10", "diagnosis_type": "comorbidity", "icd10_code": "N18.3",
         "diagnosis_name": "Bệnh thận mạn giai đoạn 3b",
         "diagnosis_text": "CKD G3b tiến triển (eGFR 35, giảm từ 38). UACR cải thiện 2200 mg/g.",
         "is_active": True, "source_system": "HIS-Diagnosis", "language": "vi"},
        {"diagnosis_id": "P006-E002-DX003", "patient_id": "P006", "encounter_id": "P006-E002",
         "diagnosis_date": "2024-09-10", "diagnosis_type": "complication", "icd10_code": "D63.1",
         "diagnosis_name": "Thiếu máu trong bệnh thận mạn",
         "diagnosis_text": "Thiếu máu mức trung bình do CKD (Hb 10.2 g/dL). Chỉ định EPO.",
         "is_active": True, "source_system": "HIS-Diagnosis", "language": "vi"},
        {"diagnosis_id": "P006-E002-DX004", "patient_id": "P006", "encounter_id": "P006-E002",
         "diagnosis_date": "2024-09-10", "diagnosis_type": "comorbidity", "icd10_code": "I10",
         "diagnosis_name": "Tăng huyết áp nguyên phát",
         "diagnosis_text": "THA. HA 148/88 mmHg, cải thiện nhưng chưa đạt mục tiêu.",
         "is_active": True, "source_system": "HIS-Diagnosis", "language": "vi"},
    ]
    dx.extend(new)
    _save("diagnoses.json", dx)


def add_vitals():
    vitals = _load("vitals.json")
    new = [
        {"vital_id": "P005-E001-VIT001", "patient_id": "P005", "encounter_id": "P005-E001",
         "measured_at": "2024-01-15T08:20:00+07:00",
         "blood_pressure_systolic": 155, "blood_pressure_diastolic": 95,
         "heart_rate": 105, "weight_kg": 65.0, "height_cm": 165.0, "bmi": 23.9,
         "abnormal_flags": ["low_spo2", "high_heart_rate", "high_blood_pressure"],
         "source_system": "EMR-Vitals", "temperature_celsius": 37.2, "spo2_percent": 84},
        {"vital_id": "P005-E002-VIT001", "patient_id": "P005", "encounter_id": "P005-E002",
         "measured_at": "2024-07-15T08:15:00+07:00",
         "blood_pressure_systolic": 138, "blood_pressure_diastolic": 85,
         "heart_rate": 82, "weight_kg": 66.0, "height_cm": 165.0, "bmi": 24.2,
         "abnormal_flags": ["low_spo2"],
         "source_system": "EMR-Vitals", "temperature_celsius": 36.6, "spo2_percent": 88},
        {"vital_id": "P005-E003-VIT001", "patient_id": "P005", "encounter_id": "P005-E003",
         "measured_at": "2024-10-15T08:10:00+07:00",
         "blood_pressure_systolic": 135, "blood_pressure_diastolic": 82,
         "heart_rate": 78, "weight_kg": 67.5, "height_cm": 165.0, "bmi": 24.8,
         "abnormal_flags": ["low_spo2"],
         "source_system": "EMR-Vitals", "temperature_celsius": 36.5, "spo2_percent": 90},
        {"vital_id": "P006-E001-VIT001", "patient_id": "P006", "encounter_id": "P006-E001",
         "measured_at": "2024-03-10T08:30:00+07:00",
         "blood_pressure_systolic": 162, "blood_pressure_diastolic": 98,
         "heart_rate": 88, "weight_kg": 72.0, "height_cm": 158.0, "bmi": 28.8,
         "abnormal_flags": ["high_blood_pressure"],
         "source_system": "EMR-Vitals", "temperature_celsius": 36.6, "spo2_percent": 97},
        {"vital_id": "P006-E002-VIT001", "patient_id": "P006", "encounter_id": "P006-E002",
         "measured_at": "2024-09-10T08:20:00+07:00",
         "blood_pressure_systolic": 148, "blood_pressure_diastolic": 88,
         "heart_rate": 82, "weight_kg": 74.0, "height_cm": 158.0, "bmi": 29.6,
         "abnormal_flags": ["high_blood_pressure"],
         "source_system": "EMR-Vitals", "temperature_celsius": 36.5, "spo2_percent": 97},
    ]
    vitals.extend(new)
    _save("vitals.json", vitals)


def add_clinical_notes():
    notes = _load("clinical_notes.json")
    new = [
        # ── P005-E001 ──
        {"note_id": "P005-E001-NOTE001", "patient_id": "P005", "encounter_id": "P005-E001",
         "note_date": "2024-01-15", "note_type": "doctor_note", "section": "history_of_present_illness",
         "text": "BN nam 70 tuổi, tiền sử hút thuốc lá 40 gói-năm, chưa bỏ. COPD Gold III phát hiện 2019. Hiện than mệt, khó thở khi đi bộ bình thường (MRC grade 4), ho đàm vàng 5 ngày nay, không sốt. Phù mắt cá nhẹ 2 bên. Tiền sử: THA 10 năm. Không đái tháo đường, không rối loạn lipid. Gia đình: bố mất do ung thư phổi năm 65 tuổi.",
         "author_id": "DR005", "author_name": "BS. Trần Minh Khoa",
         "source_system": "EMR-ClinicalNotes", "language": "vi", "text_encoding": "utf-8"},
        {"note_id": "P005-E001-NOTE002", "patient_id": "P005", "encounter_id": "P005-E001",
         "note_date": "2024-01-15", "note_type": "doctor_note", "section": "physical_exam",
         "text": "Tổng trạng trung bình, khó thở khi nói. Lồng ngực hình thùng. Rì rào phế nang giảm 2 bên, ran ngáy rải rác. Tim T2 mạnh thành phần phổi. Phù mắt cá 2 bên nhẹ, ấn lõm (+). SpO2 84% khí phòng, cải thiện 92% với oxy 2L/phút qua mũi.",
         "author_id": "DR005", "author_name": "BS. Trần Minh Khoa",
         "source_system": "EMR-ClinicalNotes", "language": "vi", "text_encoding": "utf-8"},
        {"note_id": "P005-E001-NOTE003", "patient_id": "P005", "encounter_id": "P005-E001",
         "note_date": "2024-01-15", "note_type": "doctor_note", "section": "assessment_and_plan",
         "text": "Đợt cấp COPD mức trung bình-nặng. Suy tim mất bù (BNP 680). Xử trí: (1) Oxy 2L/phút duy trì SpO2 88-92%, (2) Methylprednisolone 40mg uống 7 ngày, (3) Tiotropium + Salbutamol khi cần, (4) Furosemide 40mg + Carvedilol 6.25mg cho suy tim, (5) Tái khám 6 tháng hoặc sớm hơn nếu diễn tiến xấu.",
         "author_id": "DR005", "author_name": "BS. Trần Minh Khoa",
         "source_system": "EMR-ClinicalNotes", "language": "vi", "text_encoding": "utf-8"},
        # ── P005-E002 ──
        {"note_id": "P005-E002-NOTE001", "patient_id": "P005", "encounter_id": "P005-E002",
         "note_date": "2024-07-15", "note_type": "doctor_note", "section": "history_of_present_illness",
         "text": "Tái khám sau 6 tháng. BN bớt khó thở, đi bộ được 200m không nghỉ (MRC grade 3, cải thiện từ 4). Không ho đàm. Vẫn hút thuốc, giảm từ 20 điếu/ngày xuống 10 điếu. Phù mắt cá giảm.",
         "author_id": "DR005", "author_name": "BS. Trần Minh Khoa",
         "source_system": "EMR-ClinicalNotes", "language": "vi", "text_encoding": "utf-8"},
        {"note_id": "P005-E002-NOTE002", "patient_id": "P005", "encounter_id": "P005-E002",
         "note_date": "2024-07-15", "note_type": "doctor_note", "section": "assessment_and_plan",
         "text": "COPD Gold III ổn định. Suy tim cải thiện (BNP 420). Siêu âm tim: EF 35%, RV giãn, áp lực ĐMP ước tính 48 mmHg, van 3 lá hở nhẹ. Xử trí: (1) Thêm Fluticasone/Salmeterol ICS/LABA, (2) Tăng Carvedilol 12.5mg, Enalapril 10mg, (3) Khuyên bỏ thuốc lá mạnh mẽ, (4) Tái khám 3 tháng.",
         "author_id": "DR005", "author_name": "BS. Trần Minh Khoa",
         "source_system": "EMR-ClinicalNotes", "language": "vi", "text_encoding": "utf-8"},
        # ── P005-E003 ──
        {"note_id": "P005-E003-NOTE001", "patient_id": "P005", "encounter_id": "P005-E003",
         "note_date": "2024-10-15", "note_type": "doctor_note", "section": "history_of_present_illness",
         "text": "Tái khám 3 tháng. BN than phù mắt cá tăng hơn 2 tuần nay, khó thở khi leo cầu thang. Không ho đàm, không sốt. Đã giảm hút thuốc còn 5 điếu/ngày.",
         "author_id": "DR006", "author_name": "BS. Lê Thị Ngọc",
         "source_system": "EMR-ClinicalNotes", "language": "vi", "text_encoding": "utf-8"},
        {"note_id": "P005-E003-NOTE002", "patient_id": "P005", "encounter_id": "P005-E003",
         "note_date": "2024-10-15", "note_type": "doctor_note", "section": "assessment_and_plan",
         "text": "Suy tim EF giảm tái ứ dịch nhẹ. COPD ổn định. Xử trí: (1) Thêm Spironolactone 25mg (kháng aldosterone, chỉ định suy tim EF giảm), (2) Duy trì phác đồ hô hấp, (3) Theo dõi kali và creatinine sau 1 tuần, (4) Tái khám 3 tháng.",
         "author_id": "DR006", "author_name": "BS. Lê Thị Ngọc",
         "source_system": "EMR-ClinicalNotes", "language": "vi", "text_encoding": "utf-8"},
        # ── P006-E001 ──
        {"note_id": "P006-E001-NOTE001", "patient_id": "P006", "encounter_id": "P006-E001",
         "note_date": "2024-03-10", "note_type": "doctor_note", "section": "history_of_present_illness",
         "text": "BN nữ 45 tuổi, ĐTĐ type 2 phát hiện năm 2017, kiểm soát kém (HbA1c thường xuyên >9%). THA 3 năm. Phát hiện protein niệu nặng lần đầu tháng 12/2023 (UACR 3100 mg/g tại phòng khám khác). Hiện phù mắt cá 2 bên, mệt mỏi nhiều. Không hút thuốc. Dị ứng: Penicillin (nổi mề đay), NSAIDs (phù mạch, khó thở), Sulfonamide (chưa rõ phản ứng). Gia đình: mẹ bị CKD giai đoạn cuối, chạy thận.",
         "author_id": "DR007", "author_name": "BS. Phạm Quang Hưng",
         "source_system": "EMR-ClinicalNotes", "language": "vi", "text_encoding": "utf-8"},
        {"note_id": "P006-E001-NOTE002", "patient_id": "P006", "encounter_id": "P006-E001",
         "note_date": "2024-03-10", "note_type": "doctor_note", "section": "physical_exam",
         "text": "Tổng trạng thừa cân (BMI 28.8). Phù mắt cá 2 bên, ấn lõm (+). Da niêm hồng nhạt. Tim đều, không âm thổi. Phổi trong. Bụng mềm, không gan lách to. Mắt: không phù nề. Chuyển khám mắt kiểm tra bệnh võng mạc ĐTĐ.",
         "author_id": "DR007", "author_name": "BS. Phạm Quang Hưng",
         "source_system": "EMR-ClinicalNotes", "language": "vi", "text_encoding": "utf-8"},
        {"note_id": "P006-E001-NOTE003", "patient_id": "P006", "encounter_id": "P006-E001",
         "note_date": "2024-03-10", "note_type": "doctor_note", "section": "assessment_and_plan",
         "text": "ĐTĐ type 2 biến chứng CKD G3b A3. Chẩn đoán CKD do ĐTĐ dựa trên: eGFR 38, UACR 2800, tiền sử ĐTĐ >5 năm. Xử trí: (1) Ngừng Metformin (eGFR <45), chuyển Insulin Glargine 20 IU, (2) Losartan 100mg bảo vệ thận, (3) Calcitriol + Calcium carbonate cho rối loạn khoáng xương CKD, (4) Hạn chế đạm 0.8g/kg/ngày, muối <5g/ngày, (5) Tái khám 6 tháng, kiểm tra eGFR + UACR.",
         "author_id": "DR007", "author_name": "BS. Phạm Quang Hưng",
         "source_system": "EMR-ClinicalNotes", "language": "vi", "text_encoding": "utf-8"},
        # ── P006-E002 ──
        {"note_id": "P006-E002-NOTE001", "patient_id": "P006", "encounter_id": "P006-E002",
         "note_date": "2024-09-10", "note_type": "doctor_note", "section": "history_of_present_illness",
         "text": "Tái khám 6 tháng. BN than mệt nhiều hơn, xanh xao. Phù mắt cá giảm so với lần trước. Tuân thủ chế độ ăn hạn chế đạm tốt. Insulin tự tiêm đúng kỹ thuật nhưng glucose lúc đói vẫn 8-10 mmol/L.",
         "author_id": "DR007", "author_name": "BS. Phạm Quang Hưng",
         "source_system": "EMR-ClinicalNotes", "language": "vi", "text_encoding": "utf-8"},
        {"note_id": "P006-E002-NOTE002", "patient_id": "P006", "encounter_id": "P006-E002",
         "note_date": "2024-09-10", "note_type": "doctor_note", "section": "assessment_and_plan",
         "text": "CKD tiến triển chậm (eGFR 35, giảm từ 38). Thiếu máu mới xuất hiện (Hb 10.2 g/dL) do CKD. HbA1c cải thiện nhẹ 8.9%. UACR giảm 2200 mg/g. Xử trí: (1) Tăng Insulin 24 IU, (2) Thêm Dapagliflozin 10mg (bảo vệ thận, giảm proteinuria), (3) EPO 2000 IU 3 lần/tuần cho thiếu máu, (4) Tăng Amlodipine 10mg, (5) Khám mắt: bệnh võng mạc ĐTĐ độ II. Tái khám 3 tháng.",
         "author_id": "DR007", "author_name": "BS. Phạm Quang Hưng",
         "source_system": "EMR-ClinicalNotes", "language": "vi", "text_encoding": "utf-8"},
    ]
    notes.extend(new)
    _save("clinical_notes.json", notes)


def add_imaging():
    imaging = _load("imaging_reports.json")
    new = [
        {"imaging_id": "P005-E001-IMG001", "patient_id": "P005", "encounter_id": "P005-E001",
         "study_date": "2024-01-15", "modality": "X-quang", "body_part": "Ngực",
         "findings": "X-quang ngực PA: Phổi tăng sáng 2 bên, cơ hoành dẹt, khoang liên sườn giãn rộng — phù hợp COPD khí phế thũng. Bóng tim to sang phải (RV enlargement). Chỉ số tim-ngực 0.58 (tăng). Không thâm nhiễm phổi rõ.",
         "impression": "COPD khí phế thũng. Tim to phải, nghi tim phổi mạn. Không viêm phổi.",
         "radiologist_or_reader": "BS. Trần Minh Khoa",
         "source_system": "HIS-Imaging", "language": "vi"},
        {"imaging_id": "P005-E002-IMG001", "patient_id": "P005", "encounter_id": "P005-E002",
         "study_date": "2024-07-15", "modality": "Siêu âm tim", "body_part": "Tim",
         "findings": "Siêu âm tim qua thành ngực: Thất trái không giãn, vách liên thất bình thường. EF Simpson 35%. Thất phải giãn (TAPSE 14mm). Áp lực ĐMP ước tính 48 mmHg (tăng). Van 3 lá hở nhẹ (do giãn vòng van). Không tràn dịch màng tim.",
         "impression": "EF 35% (giảm). Suy tim phải do tăng áp phổi. Áp lực ĐMP 48 mmHg.",
         "radiologist_or_reader": "BS. Lê Thị Ngọc",
         "source_system": "HIS-Cardiology", "language": "vi"},
        {"imaging_id": "P006-E001-IMG001", "patient_id": "P006", "encounter_id": "P006-E001",
         "study_date": "2024-03-10", "modality": "Siêu âm", "body_part": "Thận",
         "findings": "Siêu âm thận 2 bên: Thận phải 9.8 cm, thận trái 9.5 cm (kích thước nhỏ hơn bình thường). Nhu mô thận tăng âm, ranh giới vỏ-tủy mờ. Vỏ thận mỏng 2 bên. Không sỏi, không ứ nước. Bàng quang bình thường.",
         "impression": "Thận teo nhỏ 2 bên, nhu mô tăng âm. Phù hợp bệnh thận mạn.",
         "radiologist_or_reader": "BS. Phạm Quang Hưng",
         "source_system": "HIS-Imaging", "language": "vi"},
        {"imaging_id": "P006-E002-IMG001", "patient_id": "P006", "encounter_id": "P006-E002",
         "study_date": "2024-09-10", "modality": "Soi đáy mắt", "body_part": "Mắt",
         "findings": "Soi đáy mắt 2 mắt: Vi phình mạch rải rác, xuất huyết chấm nhỏ, xuất tiết cứng. Không có tân mạch. Hoàng điểm bình thường.",
         "impression": "Bệnh võng mạc ĐTĐ không tăng sinh độ II 2 mắt. Không có tân mạch.",
         "radiologist_or_reader": "BS. Nguyễn Thị Mai",
         "source_system": "HIS-Imaging", "language": "vi"},
    ]
    imaging.extend(new)
    _save("imaging_reports.json", imaging)


def add_procedures():
    procs = _load("procedures.json")
    new = [
        {"procedure_id": "P005-E001-PROC001", "patient_id": "P005", "encounter_id": "P005-E001",
         "procedure_date": "2024-01-15",
         "procedure_name": "Đo chức năng hô hấp (Spirometry)",
         "source_system": "EMR-Procedures",
         "description": "Đo phế dung ký trước và sau giãn phế quản bằng Salbutamol 400 mcg. BN thực hiện 3 lần, lấy kết quả tốt nhất.",
         "result": "FEV1/FVC 0.58 (giảm, <0.70 = tắc nghẽn). FEV1 42% dự đoán (GOLD III: 30-49%). Sau giãn phế quản: FEV1 tăng 80 mL (5%) — không đáp ứng đáng kể. Kết luận: Rối loạn thông khí tắc nghẽn nặng, không hồi phục.",
         "language": "vi"},
        {"procedure_id": "P005-E002-PROC001", "patient_id": "P005", "encounter_id": "P005-E002",
         "procedure_date": "2024-07-15",
         "procedure_name": "Đánh giá mMRC dyspnea scale",
         "source_system": "EMR-Procedures",
         "description": "Đánh giá mức độ khó thở theo thang mMRC (Modified Medical Research Council).",
         "result": "mMRC grade 3 (khó thở khi đi bộ trên mặt phẳng khoảng 100m hoặc sau vài phút). Cải thiện so với lần trước (grade 4).",
         "language": "vi"},
        {"procedure_id": "P006-E001-PROC001", "patient_id": "P006", "encounter_id": "P006-E001",
         "procedure_date": "2024-03-10",
         "procedure_name": "Thu thập nước tiểu 24h — định lượng protein",
         "source_system": "EMR-Procedures",
         "description": "Thu thập nước tiểu 24 giờ để đo protein niệu toàn phần và creatinine clearance.",
         "result": "Protein niệu 24h: 4.2 g/ngày (nặng, >3.5 g = hội chứng thận hư mức). Creatinine clearance: 40 mL/phút. Thể tích nước tiểu: 1800 mL/24h.",
         "language": "vi"},
    ]
    procs.extend(new)
    _save("procedures.json", procs)


def add_allergies():
    allergies = _load("allergies.json")
    new = [
        {"allergy_id": "P006-ALLERGY001", "patient_id": "P006", "encounter_id": None,
         "recorded_date": "2020-05-10", "substance": "Penicillin",
         "reaction": "Nổi mề đay toàn thân", "severity": "moderate", "status": "active",
         "source_text": "BN báo dị ứng Penicillin năm 2020 — nổi mề đay toàn thân sau dùng Amoxicillin. Đã xác nhận.",
         "needs_patient_confirmation": False, "source_system": "EMR-Allergy", "language": "vi"},
        {"allergy_id": "P006-ALLERGY002", "patient_id": "P006", "encounter_id": None,
         "recorded_date": "2022-08-20", "substance": "NSAIDs (Ibuprofen)",
         "reaction": "Phù mạch, khó thở", "severity": "severe", "status": "active",
         "source_text": "BN dùng Ibuprofen 400mg giảm đau đầu — xuất hiện phù mạch mặt, khó thở sau 30 phút. Cấp cứu tại BV. Xác nhận dị ứng NSAIDs mức nặng.",
         "needs_patient_confirmation": False, "source_system": "EMR-Allergy", "language": "vi"},
        {"allergy_id": "P006-ALLERGY003", "patient_id": "P006", "encounter_id": None,
         "recorded_date": "2023-01-15", "substance": "Sulfonamide",
         "reaction": None, "severity": "unknown", "status": "active",
         "source_text": "BN báo dị ứng Sulfonamide nhưng không nhớ rõ phản ứng cụ thể. Cần xác nhận.",
         "needs_patient_confirmation": True, "source_system": "EMR-Allergy", "language": "vi"},
    ]
    allergies.extend(new)
    _save("allergies.json", allergies)


if __name__ == "__main__":
    print("Adding P005 + P006 data to raw files...")
    add_labs()
    add_medications()
    add_diagnoses()
    add_vitals()
    add_clinical_notes()
    add_imaging()
    add_procedures()
    add_allergies()
    print("\nDone. Run: python -m src.c1_emr.assembler")
